apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: default-cluster-stack
spec:
  serviceAccountRef:
    name: amp-controllers
    namespace: amp-system
  id: "io.buildpacks.stacks.jammy"
  buildImage:
    image: "paketobuildpacks/build-jammy-base"
  runImage:
    image: "paketobuildpacks/run-jammy-base"
