apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: amp-default-cluster-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/go
  - image: gcr.io/paketo-buildpacks/java
  - image: gcr.io/paketo-buildpacks/nodejs
  - image: gcr.io/paketo-buildpacks/php
  - image: gcr.io/paketo-buildpacks/python
  - image: gcr.io/paketo-buildpacks/ruby
  - image: docker.io/paketocommunity/rust
  - image: gcr.io/paketo-buildpacks/dotnet-core
