apiVersion: v1
kind: Secret
metadata:
  name: basic-docker-user-pass
  namespace: amp-system
  annotations:
    kpack.io/docker: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
